### ISSUE TITLE
Unexpected output from vcf2revcom.pl

### ISSUE THREAD

**Issue by HamletShaoE** [chasewnelson/EBT#1]
Dear SNPGenie/CHASeq authors:
I was in CHASeq for I would like to use CHASeq to deal with gtf, fasta and vcf for reverse strand genes/products to SNPGenie. But I got this message when I run the perl script. I was wondering if there is anything I did wrong, or I hope it would be fixed soon.

> seq length is 51304566
> 
> 
> Two products have the same starting position, causing an error.
> Please contact script author for a revision.

 

1). gtf was downloaded from an old version of Ensembl annotation (ftp://ftp.ensembl.org/pub/release-73/gtf/homo_sapiens/Homo_sapiens.GRCh37.73.gtf.gz), and filtered for CDS records whose full length are multiples of 3. These were done by the following commands (e.g. for chr22):
```
## to get the ids for only those ORFs/CDSs with both start codon and stop codon. These ORFs/CDSs should also be annotated as protein coding genes. The final ids should be gene(ENSG???????????)_transcript(ENSG???????????)
zcat Homo_sapiens.GRCh37.73.gtf.gz | awk '{if($3=="start_codon"){a[$12]=0;print $12"\tstart";} if($3=="stop_codon"){b[$12]=0;print $12"\tstop";} } ' | sort -u | cut -f1| uniq -d | sed 's/"//g;s/;//;' > tmp
zcat Homo_sapiens.GRCh37.73.gtf.gz | awk 'BEGIN{OFS="\t"} FILENAME==ARGV[1]{aa[$1]=0;} $1==22 && $2=="protein_coding" && $3=="CDS"{split($10,a,"\"");split($12,b,"\"");if(b[2] in aa){print $1,$2,$3,$4,$5,$6,$7,$8,"gene_id \""a[2]"_"b[2]"\"";}}' tmp - > chr22.gtf
## to filter for ORFs/CDSs whose length are multiples of 3.
sort -k9 -k4 chr22.gtf | awk ' {if($10==a){len=$5-$4+1+len;}else{if(len % 3 != 0 ){print a;}a=$10;len=$5-$4+1; } } END{if(len % 3 != 0 ){print a;}}' > tmp
grep -v -f tmp chr22.gtf > chr22.filter.gtf
```
2). The vcf was downloaded from OneKGenome phase 3(http://www.internationalgenome.org/data and more specificly ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/).
3). I got fasta file from UCSC (http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz).
4). I run vcf2revcom.pl
vcf2revcom.pl  chr22.fa chr22.filter.gtf ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf
P.S. the order of input is not vcf, fasta and then gtf as written in the git page (https://github.com/chasewnelson/CHASeq). But instead the order above.

**Comment by HamletShaoE** [comment]
These 3 input files runs well for the genes/products on the plus/+ strand, when I call SNPGenie in the following command:
`~/rd/program/snpgenie/snpgenie.pl --sepfiles --sitebasedmode --minfreq=0.01 --snpreport=ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf --vcfformat=1 --fastafile=chr22.fa --gtffile=chr22.filter.gtf`

**Comment by singing-scientist** [comment]
Thanks for inquiring about this script, HamletShaoE! Sorry that the example call is in the wrong order — I'll change that now. 

The script itself is only designed to handle GTFs where every CDS record has a unique starting position. Assuming it's okay that you have duplicate start sites, I'll go ahead and update the script for you within ~24hrs. In the meantime, please provide a small sample FASTA, VCF, and GTF file using Dropbox and/or Google Drive so I can better ensure it's working for you.

Will be in touch soon!

**Comment by singing-scientist** [comment]
> These 3 input files runs while for the genes/products on the plus/+ strand, when I call SNPGenie in the following command:

Do you mean to say it works well for this strand? If so, excellent!

**Comment by HamletShaoE** [comment]
I already share the data via dropbox to cnelson (at) amnh.org.
Yes, 'while' -> 'well', sorry for the typo. SNPGenie completed successfully for the plus strand. Proving these data I use is right.

**Comment by singing-scientist** [comment]
vcf2revcom.pl has now been updated. Please let me know if it works for your data and, if so, I'll close the issue. Thanks!

**Comment by HamletShaoE** [comment]
Thank you for your timely update and reply. It works for my data on chr22 now.
Even though the script report warnings ### FILE TYPE NOT FULLY SUPPORTED### for every vcf line, I got the output SNP report which are correct for the first few lines I checked manually.
Another suggestion for users is that, for the fasta file may be soft-masked (some nucleotide are in lower case), users should first convert all nucleotides in the fasta file into upper case (cat chr22.fa | tr 'atcg' 'ATCG' > chr22.Upper.fa). Otherwise, the script shall report an error:
```
Substring: c
Ref: G

## WARNING: New nucleotide at site 35254040 does not match reverse complement. SNPGenie terminatred
```
Anyway, this is easy to fix on users side. So just a little tip, never mind.
Again, thanks for your efforts and patience. I really appreciate your help.

**Comment by singing-scientist** [comment]
Thanks very much for your help with troubleshooting and debugging! I will definitely add this tip to the documentation and considering allowing lowercase in the future. Please let me know if you have any other issues!
